GET http://localhost:5000/timeline/1
Accept: application/json

### unfollow

POST http://localhost:5000/unfollow
Content-Type: application/json

{
  "id": 1,
  "unfollow": 2
}

### follow
POST http://localhost:5000/follow
Content-Type: application/json

{
  "id": 1,
  "follow": 2
}

### tweet
POST http://localhost:5000/tweet
Content-Type: application/json

{
  "id": 1,
  "tweet": "My First Tweet"
}

### tweet
POST http://localhost:5000/tweet
Content-Type: application/json

{
  "id": 2,
  "tweet": "언젠가는 훌륭한 백엔드 개발자가 될 거야"
}

### sign-up
POST http://localhost:5000/sign-up
Content-Type: application/json

{
  "name": "송은우",
  "email": "songew@gmail.com",
  "password": "test1234",
  "profile": "software engineer. book author"
}

###