POST http://localhost:5000/tweet
Content-Type: application/json

{
  "id": 1,
  "tweet": "My First Tweet"
}

###
POST http://localhost:5000/sign-up
Content-Type: application/json

{
  "name": "송은우",
  "email": "songew@gmail.com",
  "password": "test1234",
  "profile": "software engineer. book author"
}

###